// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubscriptionService.Infrastructure;

#nullable disable

namespace SubscriptionService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubscriptionService.Domain.Aggregates.Plan.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_period");

                    b.Property<DateTimeOffset>("CreatedWhen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_when");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "SubscriptionService.Domain.Aggregates.Plan.Plan.Name#PlanName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "SubscriptionService.Domain.Aggregates.Plan.Plan.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price");
                        });

                    b.HasKey("Id");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("SubscriptionService.Domain.Aggregates.Subscription.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset?>("CancelledWhen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_when");

                    b.Property<DateTimeOffset>("CreatedWhen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_when");

                    b.Property<DateTimeOffset>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset?>("ExpiredWhen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_when");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TrialEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_end");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_subscriptions_user_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("SubscriptionService.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedWhen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_when");

                    b.Property<bool>("HasUsedTrial")
                        .HasColumnType("boolean")
                        .HasColumnName("has_used_trial");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "SubscriptionService.Domain.Aggregates.User.Email#UserEmail", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");
                        });

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SubscriptionService.Domain.Aggregates.Subscription.Subscription", b =>
                {
                    b.OwnsMany("SubscriptionService.Domain.Aggregates.Subscription.Invoice", "Invoices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("CreatedWhen")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_when");

                            b1.Property<DateTimeOffset>("DueDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("due_date");

                            b1.Property<DateTimeOffset?>("PaidWhen")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("paid_when");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SubscriptionId");

                            b1.ToTable("invoices", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");

                            b1.OwnsOne("SubscriptionService.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("InvoiceId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("amount");

                                    b2.HasKey("InvoiceId");

                                    b2.ToTable("invoices");

                                    b2.WithOwner()
                                        .HasForeignKey("InvoiceId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
